### ISSUE TITLE
Missing NL_BORDER.geojson file

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/stac-ml-example#2]
The notebook references the `NL_BORDER.geojson` file which is not found in the repo, probably forgot to add it.

Thanks!

**Comment by chorng** [comment]
Added by [pr #3 ](https://github.com/sentinel-hub/stac-ml-example/pull/3)

**Comment by chorng** [comment]
Added `NL_BORDER.geojson` to `data` as referenced in the notebook.
